- project:
    templates:
      - check-requirements
      - openstack-cover-jobs-neutron
      - openstack-python3-wallaby-jobs-neutron
      - periodic-stable-jobs-neutron
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - neutron-vpnaas-functional-sswan
        - neutron-tempest-plugin-vpnaas-wallaby
    gate:
      jobs:
        - neutron-vpnaas-functional-sswan
        - neutron-tempest-plugin-vpnaas-wallaby
    experimental:
      jobs:
        - neutron-vpnaas-rally

- job:
    name: neutron-vpnaas-functional-sswan
    parent: neutron-functional
    pre-run: playbooks/configure_functional_job.yaml
    vars:
      project_name: neutron-vpnaas
      tox_envlist: dsvm-functional-sswan

- job:
    name: neutron-vpnaas-rally
    parent: rally-task-neutron
    timeout: 7800
    vars:
      devstack_plugins:
        rally-openstack: https://opendev.org/openstack/rally-openstack
        neutron-vpnaas: https://opendev.org/openstack/neutron-vpnaas
      rally_task: rally-jobs/rally-configs/rally_config_dvr.yaml
    required-projects:
      - openstack/devstack-gate
      - openstack/neutron
      - openstack/neutron-vpnaas
      - openstack/rally
      - openstack/rally-openstack
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^neutron_vpnaas/tests/unit/.*$
      - ^releasenotes/.*$
