- project:
    templates:
      - check-requirements
      - periodic-stable-jobs-neutron
      - openstack-python-jobs-neutron
      - openstack-python35-jobs-neutron
      - publish-openstack-sphinx-docs
      - release-notes-jobs
    check:
      jobs:
        - neutron-vpnaas-dsvm-functional-sswan
        - neutron-vpnaas-dsvm-tempest
        - openstack-tox-cover:
            voting: false
            required-projects:
              - openstack/neutron

    gate:
      jobs:
        - neutron-vpnaas-dsvm-functional-sswan
        - neutron-vpnaas-dsvm-tempest
    experimental:
      jobs:
        - neutron-vpnaas-dsvm-rally

- job:
    name: neutron-vpnaas-dsvm-tempest
    parent: legacy-dsvm-base
    run: playbooks/legacy/neutron-vpnaas-dsvm-tempest/run.yaml
    post-run: playbooks/legacy/neutron-vpnaas-dsvm-tempest/post.yaml
    timeout: 3900
    required-projects:
      - openstack/devstack-gate
      - openstack/neutron
      - openstack/tempest
      - openstack/neutron-tempest-plugin

- job:
    name: neutron-vpnaas-dsvm-functional-sswan
    parent: legacy-dsvm-base
    run: playbooks/legacy/neutron-vpnaas-dsvm-functional-sswan/run.yaml
    post-run: playbooks/legacy/neutron-vpnaas-dsvm-functional-sswan/post.yaml
    timeout: 7800
    required-projects:
      - openstack/devstack-gate
      - openstack/neutron
      - openstack/neutron-vpnaas
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^neutron-vpnaas/tests/unit/.*$

- job:
    name: neutron-vpnaas-dsvm-rally
    parent: legacy-dsvm-base
    run: playbooks/legacy/neutron-vpnaas-dsvm-rally/run.yaml
    post-run: playbooks/legacy/neutron-vpnaas-dsvm-rally/post.yaml
    timeout: 7800
    required-projects:
      - openstack/devstack-gate
      - openstack/neutron
      - openstack/neutron-vpnaas
      - openstack/rally
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^neutron-vpnaas/tests/unit/.*$

